### ISSUE TITLE
请问代码要怎么运行？

### ISSUE THREAD

**Issue by JinChengneng** [licstar/compare#1]
你好，我是刚开始学习自然语言处理的大三学生，在尝试运行您提供的源代码的过程中一直出错。请问是只要按evaluation中的README的指导操作就行了吗？embedding包中的代码需要运行吗？敬请赐教，不胜感激。

**Comment by licstar** [comment]
如果你已经有训练好的embedding，可以直接按照evaluation中的指导操作

**Comment by JinChengneng** [comment]
谢谢解答。我已经通过阅读您的源码找到运行的方法，并成功复现了。
